########################################################################################################
########################################################################################################
#
#     Just run this file over and over
#
#
########################################################################################################
########################################################################################################

# Notes:

# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
# 


version: 0.2

env:
  variables:
    whatismypurpos: "Create the cloudformation template with the SSM Documents for Phase 2"
phases:
  install:
    commands:
      - echo no install necessary
      - echo $codecommithttpsurl
      - echo $codecommithttpsname
      - echo $codepipelinesnstopicarn

  pre_build:
    commands:
      - pwd
      - ls -al 
      - echo $CODEBUILD_INITIATOR
      - CODEBUILD_INITIATOR_SERVICE="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f1)"
      - CODEBUILD_INITIATOR_NAME="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f2)"
      - echo $CODEBUILD_INITIATOR_NAME


  build:
    commands:
      - aws cloudformation deploy --stack-name $CODEBUILD_INITIATOR_NAME-step-function --template-file cloudformation_step_function.yaml --parameter-overrides PipelineName=$CODEBUILD_INITIATOR_NAME GitHTTPSURL=$codecommithttpsurl GitRepoName=$codecommithttpsname --capabilities CAPABILITY_IAM --tags createdby=DevOps --no-fail-on-empty-changeset

  post_build:
    commands:
      - echo NO STEPS IN POST_BUILD stage
      # - command

# artifacts:
#   files:
#     # - location
#     # - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - path
#     - path























