########################################################################################################
########################################################################################################
#
#     Just run this file over and over
#
#
########################################################################################################
########################################################################################################

# Notes:

# This is intended to run in the SIRRR Staging AWS Account 
# https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html
# 


version: 0.2

env:
  variables:
    key1: "value1"
    key2: "value2"
  # parameter-store:
    # AD_PASSWORD2: "/autocleanup/ad_password"


phases:
  install:
    commands:
      - echo $CODEBUILD_INITIATOR
      - CODEBUILD_INITIATOR_SERVICE="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f1)"
      - CODEBUILD_INITIATOR_NAME="$(echo $CODEBUILD_INITIATOR | cut -d'/' -f2)"
      - echo $CODEBUILD_INITIATOR_NAME
      - AD_PASSWORDSSMPARAMETERNAME=$CODEBUILD_INITIATOR_NAME-AD_PASSWORD
      - echo $AD_PASSWORDSSMPARAMETERNAME
      - AD_PASSWORD=$(aws ssm get-parameter --name $AD_PASSWORDSSMPARAMETERNAME --with-decryption --region $AWS_REGION --output text | awk '{print $6}')
      # - echo $AD_PASSWORD
      - PIPELINENAME=$CODEBUILD_INITIATOR_NAME
      - echo PIPELINENAME=
      - echo $PIPELINENAME      
      # - command

  pre_build:
    commands:
      - pwd
      - ls -al 

  build:
    commands:
      - aws cloudformation deploy --stack-name $CODEBUILD_INITIATOR_NAME-activedirectory --template-file cloudformation_activedirectory_domain.yaml --parameter-overrides PipelineName=$CODEBUILD_INITIATOR_NAME DomainAdminPassword=$AD_PASSWORD DomainDNSName=greatcalldevops.com DomainNetBIOSName=greatcalldevops --capabilities CAPABILITY_IAM --tags createdby=DevOps --no-fail-on-empty-changeset
      # - aws cloudformation deploy --stack-name 'autocleanup' --template-file autocleanup_vpc.yaml --parameter-overrides Environment=DEV CIDRRangePrefix=10.250 --capabilities CAPABILITY_IAM --tags createdby=DevOps --no-execute-changeset
      # - aws cloudformation create-stack --stack-name 'autocleanup-build-pipeline' --template-body file:///autocleanup_vpc.yaml --parameters ParameterKey=Environment,ParameterValue=DEV ParameterKey=CIDRRangePrefix,ParameterValue=10.250.0.0/16 --capabilities CAPABILITY_IAM || true
      # - aws cloudformation update-stack --stack-name 'autocleanup-build-pipeline' --template-body file:///autocleanup_vpc.yaml --parameters ParameterKey=Environment,ParameterValue=DEV ParameterKey=CIDRRangePrefix,ParameterValue=10.250.0.0/16 --capabilities CAPABILITY_IAM || true

  post_build:
    commands:
      - echo NO STEPS IN POST_BUILD stage
      # - command

# artifacts:
#   files:
#     # - location
#     # - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - path
#     - path












